sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull fedora:25
  
script:
- docker run --privileged -it fedora:25 /bin/sh -c "dnf -y install git python-pip inkscape; pip instlal --upgrade pip; pip install meson ninja requests cairosvg Pillow;"
- docker run  -it fedora:25 /bin/sh -c "git clone https://github.com/bil-elmoussaoui/Icon-Requests; cd ./Icon-Requests; mkdir build; cd ./build; meson ..; ninja;"
- docker run --privileged -it fedora:25 /bin/sh -c "ninja install"
- docker run  -it fedora:25 /bin/sh -c "icon-requests"
